name: DOLL AUR CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Execute package update."
        run: sudo apt-get update
      - name: "Install dependencies."
        run: sudo apt-get install -y pacman
      - name: "Test commands."
        run: makepkg && repo-add
      - name: "Deploy repository if present."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: output
